import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// The Storyblok Client & hook
import Storyblok, { useStoryblok } from "../lib/storyblok";
import DynamicComponent from '../components/DynamicComponent'


export default function Home(props, preview) {
  const enableBridge = true; // load the storyblok bridge everywhere
  // const enableBridge = preview; // enable bridge only in prevew mode
 
  //story = useStoryblok(story, enableBridge);

  const story = props.story

  props = useStoryblok(story, enableBridge);

  return (
    <div className={styles.container}>
      <Head>
        <title>Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <div>
      <DynamicComponent blok={story.content} /> 
      </div> 
     

    </div>
  )
}

export async function getStaticProps({ preview = false }) {
  // home is the default slug for the homepage in Storyblok
  let slug = "home";
  // load the published content outside of the preview mode
  let sbParams = {
    version: "draft", // or 'published'
    resolve_relations:"myArticles.articles"
  };
 
  if (preview) {
    // load the draft version inside of the preview mode
    sbParams.version = "draft";
    sbParams.cv = Date.now();
  }
 
  let { data } = await Storyblok.get(`cdn/stories/${slug}`,sbParams);
 
  return {
    props: {
      story: data ? data.story : null,
      preview,
    },
    revalidate: 3600, // revalidate every hour
  };
}